sudo: false
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
before_install: gem install bundler
env:
  global:
    - CC_TEST_REPORTER_ID=7e9fdb9b0066c819e6f0554e4ac81255f4f01d8da2a42ac1152402797e927401
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
